use_frameworks!

target 'TvRemote_Example' do
  pod 'TvRemote', :path => '../'
  

  target 'TvRemote_Tests' do
    inherit! :search_paths

    
  end
end

target 'TV' do
    pod 'TvRemote', :path => '../'
end
